M48
; DRILL file {KiCad (6.0.0)} date Sat Mar 19 15:47:24 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-19T15:47:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X8.523Y-16.0
X163.974Y-16.0
T1
X6.943Y-3.0G85X7.943Y-3.0
G05
X164.604Y-3.0G85X165.604Y-3.0
G05
T0
M30
